baseURL = "https://cuellarcarlos28.github.io/my_launchx_blog/"
languageCode = "en-us"
title = "BitÃ¡cora de Viaje"
theme = "hugo-winston-theme"
relativeURLs = true
canonifyURLs = true

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[params]
  google_analytics_id = "G-XV1XG7J445"
  # Hey Explorer aquÃ­ pon tu twitter ðŸ‘‡
  twitter_handle = "CuellarCarlos28"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  addFrame = true
  addDot = true
